import { heightPercentageToDP as hp, widthPercentageToDP as wp } from "react-native-responsive-screen";

const CONSTANTS = {
    BG_COLOR_1 : "#E6F6FF",
    BG_COLOR_2 : "#ffffff",
    COLOR_GREY_ONE : "#525e66",
    COLOR_GREY_TWO : "#222a2d",
    COLOR_GOLD_ONE : "#f9cc71",
    COLOR_GOLD_TWO : "#f3b269",
    COLOR_RED_ONE : "#d92f2f",
    COLOR_RED_TWO : "#b20a09",
    COLOR_GREEN : "green",
    COLOR_FONT: "#525e66",
    COLOR_WHITE: '#fff',
    COLOR_BLACK: '#000',
    COLOR_DASHBOARD_LEFT: "#99875d",
    COLOR_DASHBOARD_RIGHT: "#313a3f",
    COLOR_TRANSPARENT: 'rgba(0,0,0,0.75)',
    COLOR_ALERT_RED: '#cc3300',
    LIGHT_RED: '#fef3ec',
    WHITE_GREY: '#d4d4d4',
    BLUE: '#3543bf',
    ORANGE: '#fe7d32',
    GREEN: '#30a960',
    RED: '#f06159',
    BLACK: '#0b0b0b',
    SILVER: '#efefef',
    WHITE: '#fff',
    GREY: '#7e7e7e',
    FONT_SIZE: wp('5%'),
    COLOR_BUTTON_1 : "#3F5A6E",    
    COLOR_BUTTON_GOOGLE : "#E61922",
    COLOR_BUTTON_FACEBOOK : "#007FB3",    
    COLOR_BUTTON_EMAIL : "#247500",
    COLOR_BUTTON_SUBMIT : "#007FB3",
    COLOR_BUTTON_SUBMIT1 : "#37ACFA",
}

export default CONSTANTS;